### ISSUE TITLE
Difference between bert-as-service and pretrained-pytorch-BERT

### ISSUE THREAD

**Issue by tcqiuyu** [jina-ai/clip-as-service#318]
Hi,

I wondered if anybody knows the difference between the `BertModel` of [pytorch-pretrained-BERT](https://github.com/huggingface/pytorch-pretrained-BERT) and bert-as-service.

I cannot get the same result between these two even if I use the same checkpoint. pytorch-pretrained-BERT yield a lower acc and slower convergence.

The memory usage of BertModel seems much higher than bert-as-service. With the same batch-size=32, max_seq_len=100, the bert-as-service will take about 8000MB but BertModel will cost more than 16000MB because I got an OOM issue.

Does any one knows the reason behind it? Is there any optimization done for bert-as-service?

**Comment by hanxiao** [comment]
you may want to read the tech details: https://hanxiao.github.io/2019/01/02/Serving-Google-BERT-in-Production-using-Tensorflow-and-ZeroMQ#Serving-with-low-latency
