### ISSUE TITLE
Bert-serving-start cannot work

### ISSUE THREAD

**Issue by junrong1** [jina-ai/clip-as-service#502]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.0
- Python version: 3.6
- `bert-as-service` version: 1.10
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

PS C:\Users\Junrong Yao\Appdata\Local\Programs\Python\Python36> bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12
```

Then this issue shows up:

c:\users\junrong yao\appdata\local\programs\python\python36\lib\site-packages\bert_serving\server\helper.py:176: UserWarning: Tensorflow 2.0.0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/
  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)
usage: C:\Users\Junrong Yao\AppData\Local\Programs\Python\Python36\Scripts\bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
       do_lower_case = True
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /tmp/english_L-12_H-768_A-12
no_position_embeddings = False
    no_special_token = False
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
c:\users\junrong yao\appdata\local\programs\python\python36\lib\site-packages\bert_serving\server\helper.py:176: UserWarning: Tensorflow 2.0.0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/
  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\users\junrong yao\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\junrong yao\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Junrong Yao\AppData\Local\Programs\Python\Python36\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "c:\users\junrong yao\appdata\local\programs\python\python36\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\users\junrong yao\appdata\local\programs\python\python36\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

**Comment by goodhamgupta** [comment]
Hi @junrong1 

You have not downloaded the BERT model and stored it in the `/tmp/english_L-12_H-768_A-12` folder, due to which you are facing the above error. Download the models from the links mentioned in the README.md, unzip the downloaded file and try the `bert-serving-start` command again.

**Comment by junrong1** [comment]
Hi @goodhamgupta 
I downladed the BERT and put it under the  `server/tmp/english_L-12_H-768_A-12` folder, is this path wrong, anywhere else should I put. By the way, I also tried the absolute path for `-model_dir` but still not work with the same problem.

**Comment by murtaza98** [comment]
U r on a Windows so u will have to change the forward slash(/) to backward slash(\)

so ur cmd should be like
`bert-serving-start -model_dir tmp\english_L-12_H-768_A-12`

**Comment by tilmanbeck** [comment]
Hi @junrong1 ,

I faced the same problem. The problem for me was the tensorflow version, I downgraded it to 1.10 and then it worked.

I hope this can be helpful
