### ISSUE TITLE
Cannot send tensor to the encode() function 

### ISSUE THREAD

**Issue by shubham-goel-zefr** [jina-ai/clip-as-service#677]
The CLIPEncoder only works with the `.uri` and `.blob` objects when sending a `encode()` request. Here - 

https://github.com/jina-ai/clip-as-service/blob/fa42dc50f6c766c60fe246802ecc8c15e37fbdf4/server/clip_server/executors/clip_torch.py#L40

If a `.tensor` is available in the `Document`, there shouldn't be a need to use `.uri` or `.blob` to create a PIL Image which is sent to the _preprocess function, and the tensor itself could be used for that purpose.

**Comment by numb3r3** [comment]
According to the doc https://clip-as-service.jina.ai/user-guides/client/#input-as-iterable-of-documents, clip-as-service (CaS) now only accepts `.uri` and `.blob` as the image attribute. 
> each Document must be filled with `.text` or `.uri` or `.blob` attribute. Document filled with `.text` is considered as sentence, Document filled with `.uri` or `.blob` is considered as image.

However, it makes sense to allow `.tensor` as the image input.

**Comment by hanxiao** [comment]
https://clip-as-service.jina.ai/user-guides/client/#input-as-iterable-of-documents 

supported in `0.1.13`

**Comment by shubham-goel-zefr** [comment]
@hanxiao that was quick. Awesome thanks!

**Comment by shubham-goel-zefr** [comment]
@hanxiao it looks like the tensor `document` doesn't work if the Document doesn't contain a valid `URI`. And it seems to be loading the `URI` into a blob, so I'm not sure if it's using the `tensor` or the `blob` to generate the final embedding. Any help is appreciated.

**Comment by numb3r3** [comment]
@shubham-goel-zefr thanks for your report, fix is rolled out in `v0.1.14`, you can try it out.

**Comment by shubham-goel-zefr** [comment]
@numb3r3  It's throwing an error on this line:
https://github.com/jina-ai/clip-as-service/blob/bfd047061d7465877503caa3f11f77065718cbc4/client/clip_client/client.py#L138

**Comment by numb3r3** [comment]
have you upgraded to `v0.1.14`? If yes, may I get your script to help me to reproduce your error?

**Comment by shubham-goel-zefr** [comment]
Yes I've upgraded it. Here is the code to reproduce it
` from clip_client import Client
c = Client('grpc://0.0.0.0:51000')
imgs = glob("path_to_images/*")
pil_images = [Image.open(img) for img in imgs]
docs_with_tensor = [Document(tensor=np.array(img)) for img in pil_images[:100]]
da= DocumentArray(docs_with_tensor)
r = c.encode(da, batch_size=1, show_progress=True)
`

**Comment by numb3r3** [comment]
Your script works on my side. I guess the upgrading failed. Could you try upgrade via
```
pip install --upgrade clip_server
```

**Comment by shubham-goel-zefr** [comment]
It's working. I forgot to restart my `clip-client`. Sorry for the trouble. Thanks for fixing it

**Comment by numb3r3** [comment]
perfect. hope you enjoy the service. Any feedbacks are welcome!
