### ISSUE TITLE
想问下，按照readme操作的，测试了1000条图像编码，时间是0.1s/张，没有到0.01s/张

### ISSUE THREAD

**Issue by will-wiki** [jina-ai/clip-as-service#686]
python3.8、cuda10.1、torch1.7.1+cu101测试过了能调用gpu

代码如下：
import time
from clip_client import Client

c = Client('grpc://10.190.153.14:51000')
num = 1000
start = time.time()
 for _ in range(num):
    r = c.encode(['COCO_val2014_000000558911.jpg'])  # local image
 end = time.time()

 print(f"cost:{(end-start)/num}")

**Comment by hanxiao** [comment]
Thanks for trying. Hint. Avoid `for` loop. Instead, use DocArray, your code can be rewritten as the follows.

```python
import time

from clip_client import Client

c = Client('grpc://10.190.153.14:51000')

num = 1_000

da = DocumentArray(Document(uri='COCO_val2014_000000558911.jpg') for _ in range(num))

start = time.perf_counter()
r = c.encode(da, show_progress=True)
end = time.perf_counter()

print(f'cost:{(end - start) / num}')
```

**Comment by hanxiao** [comment]
@MrBeeMovie for now, please consider use `.encode(.iter)` instead of `iter(.encode())` as I mentioned in the comment above
