### ISSUE TITLE
executing "python -m clip_server" but fail 

### ISSUE THREAD

**Issue by LioHaunt** [jina-ai/clip-as-service#690]
Hi,

Sorry for disturbing you. When executed "python -m clip_server" but fail, I search the problem in the issues, and excuted _pip install --upgrade jina>=3.3.4 clip-server>=0.2.1_ , but it didnt work…

Below is the complete stack info. I would appreciate it if you could help me.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
1/2 waiting clip_t to be ready...   clip_t/rep-0@16796[C]:can not load the executor from {"jtype": "CLIPEncoder", "metas": {"py_modules": ["executors/clip_torch.py"]}}
   clip_t/rep-0@16796[E]:ExecutorFailToLoad() during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\clip_server\model\clip.py", line 178, in load
    model = torch.jit.load(model_path, map_location=device if jit else 'cpu').eval()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\request_handlers\data_request_handler.py", line 48, in _load_executor
    self._executor: BaseExecutor = BaseExecutor.load_config(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\jaml\__init__.py", line 753, in load_config
    return JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\jaml\__init__.py", line 175, in load
    r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\jaml\__init__.py", line 575, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\jaml\parsers\executor\legacy.py", line 75, in parse
    obj = cls(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\executors\decorators.py", line 71, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\clip_server\executors\clip_torch.py", line 49, in __init__
    self._model, self._preprocess_blob, self._preprocess_tensor = clip.load(
  File "C:\ProgramData\Anaconda3\lib\site-packages\clip_server\model\clip.py", line 187, in load
    state_dict = torch.load(model_path, map_location='cpu')
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\orchestrate\pods\__init__.py", line 74, in run
    runtime = runtime_cls(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\worker\__init__.py", line 32, in __init__
    super().__init__(args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\asyncio.py", line 67, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\worker\__init__.py", line 38, in async_setup
    await self._async_setup_grpc_server()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\worker\__init__.py", line 64, in _async_setup_grpc_server
    self._data_request_handler = DataRequestHandler(
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\request_handlers\data_request_handler.py", line 40, in __init__
    self._load_executor(metrics_registry)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jina\serve\runtimes\request_handlers\data_request_handler.py", line 76, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
⠧ 1/2 waiting clip_t to be ready...           Flow@37832[E]:Flow is aborted due to ['clip_t'] can not be started.
⠏ 2/2 waiting  to be ready...  gateway/rep-0@37832[W]:Pod was forced to close after 1 second. Graceful closing is not available on Windows.
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│                                                                                                  │
│ C:\ProgramData\Anaconda3\lib\runpy.py:197 in _run_module_as_main                                 │
│                                                                                                  │
│   194 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   195 │   if alter_argv:                                                                         │
│   196 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ > 197 │   return _run_code(code, main_globals, None,                                             │
│   198 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   199                                                                                            │
│   200 def run_module(mod_name, init_globals=None,                                                │
│ C:\ProgramData\Anaconda3\lib\runpy.py:87 in _run_code                                            │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ >  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\lib\site-packages\clip_server\__main__.py:11 in <module>                │
│                                                                                                  │
│    8 │   │   'torch-flow.yml' if len(sys.argv) == 1 else sys.argv[1],                            │
│    9 │   │   extra_search_paths=[os.path.dirname(inspect.getfile(inspect.currentframe()))],      │
│   10 │   )                                                                                       │
│ > 11 │   with f:                                                                                 │
│   12 │   │   f.block()                                                                           │
│   13                                                                                             │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\lib\site-packages\jina\orchestrate\flow\base.py:1122 in __enter__       │
│                                                                                                  │
│   1119 │                                                                                         │
│   1120 │   def __enter__(self):                                                                  │
│   1121 │   │   with CatchAllCleanupContextManager(self):                                         │
│ > 1122 │   │   │   return self.start()                                                           │
│   1123 │                                                                                         │
│   1124 │   def __exit__(self, exc_type, exc_val, exc_tb):                                        │
│   1125 │   │   if hasattr(self, '_stop_event'):                                                  │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\lib\site-packages\jina\orchestrate\flow\base.py:1177 in start           │
│                                                                                                  │
│   1174 │   │   │   if not v.external:                                                            │
│   1175 │   │   │   │   self.enter_context(v)                                                     │
│   1176 │   │                                                                                     │
│ > 1177 │   │   self._wait_until_all_ready()                                                      │
│   1178 │   │                                                                                     │
│   1179 │   │   self._build_level = FlowBuildLevel.RUNNING                                        │
│   1180                                                                                           │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\lib\site-packages\jina\orchestrate\flow\base.py:1257 in                 │
│ _wait_until_all_ready                                                                            │
│                                                                                                  │
│   1254 │   │   │   │   │   f'Flow is aborted due to {error_deployments} can not be started.'     │
│   1255 │   │   │   │   )                                                                         │
│   1256 │   │   │   │   self.close()                                                              │
│ > 1257 │   │   │   │   raise RuntimeFailToStart                                                  │
│   1258 │   │                                                                                     │
│   1259 │   │   if addr_table:                                                                    │
│   1260 │   │   │   print(                                                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeFailToStart

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

Below is the clip_server version
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Name: clip-server
Version: 0.2.1
Summary: Embed images and sentences into fixed-length vectors via CLIP
Home-page: https://github.com/jina-ai/clip-as-service
Author: Jina AI
Author-email: hello@jina.ai
License: Apache 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires: torch, docarray, jina, ftfy, regex, torchvision
Required-by:

**Comment by LioHaunt** [comment]
i deleted the file and reinstall ，and the problem solved.

**Comment by numb3r3** [comment]
@LioHaunt  maybe my response is too late. The reason behind is that the model downloading procedure is interrupted the first time. Then, the downloading cannot be resumed and the local model file cannot be loaded. 

Anyway, this problem has been addressed and released in `v0.2.2`.

**Comment by LioHaunt** [comment]
> 

yes，I do interrupted the model downloading procedure>_<, and i deleted all the file related then the problem solved. anyway, thank you for your response^_^.

**Comment by LioHaunt** [comment]
> @LioHaunt maybe my response is too late. The reason behind is that the model downloading procedure is interrupted the first time. Then, the downloading cannot be resumed and the local model file cannot be loaded.
> 
> Anyway, this problem has been addressed and released in `v0.2.2`.

yes，I do interrupted the model downloading procedure>_<, and i deleted all the file related then the problem solved. anyway, thank you for your response^_^.
