### ISSUE TITLE
when excuting python -m clip_server, the Public address doesnt appear…

### ISSUE THREAD

**Issue by LioHaunt** [jina-ai/clip-as-service#691]
![图片](https://user-images.githubusercontent.com/100932755/164890354-810fe8f2-193b-4ba3-85ca-1839d15ec460.png)
it has been remained like this for a long time, is that normal TAT?

**Comment by numb3r3** [comment]
well, this is maybe caused by the network problem. BTW, does the started service can handle requests?

**Comment by numb3r3** [comment]
some more detailed explanation about this problem. https://github.com/jina-ai/clip-as-service/issues/692#issuecomment-1107791827

**Comment by LioHaunt** [comment]
> 

thank u for the response， I just found that no public address doesnt affect my task. only local access is enough.
