### ISSUE TITLE
运行python -m clip_server时，一直加载不出public network

### ISSUE THREAD

**Issue by LioHaunt** [jina-ai/clip-as-service#692]
![图片](https://user-images.githubusercontent.com/100932755/164909775-f3786388-a07d-4c3d-96db-aa3d40d7b61b.png)

**Comment by numb3r3** [comment]
可以响应请求吗？

**Comment by hanxiao** [comment]
Public IP lookup depends on third-party service, which may timeout due to your network condition. This, however, should not affect how you use the service. If you need the public IP to use the service, you will have to look up by yourself, e.g. google/baidu "what is my IP address"

**Comment by LioHaunt** [comment]
> 可以响应请求吗？

可以的

**Comment by LioHaunt** [comment]
> Public IP lookup depends on third-party service, which may timeout due to your network condition. This, however, should not affect how you use the service. If you need the public IP to use the service, you will have to look up by yourself, e.g. google/baidu "what is my IP address"

thank u for the response， I just found that no public address doesnt affect my task. only local access is enough.
