### ISSUE TITLE
Can we use it in tensorflow 1.15 or 1.13?

### ISSUE THREAD

**Issue by username123062** [jina-ai/clip-as-service#693]

**Comment by numb3r3** [comment]
That's a good question. My concern is are there any benefits to supporting tensorflow? For inference efficiency, we can use `onnx` and `tensorrt` (`tensorrt` backend is on the road) on CPU and GPU respectively. What's more, almost all of the pre-trained models are pytorch.

**Comment by hanxiao** [comment]
i think @username123062 was talking about the old bert-as-service, please consider use the actively maintained CLIP-as-service

**Comment by username123062** [comment]
Because my work is based on tensorflow 1.13 platform, and I want to add the clipt text part with current ckpt to compute the loss

**Comment by numb3r3** [comment]
any trouble to use onnx in your case?

**Comment by username123062** [comment]
> 

Many problems. My work is based on:

python 2.7
tensorflow 1.15 or 1.13
onnx < 1.7.0 
(if onnx >1.7.0, an error will be "Failed to build onnx
ERROR: Could not build wheels for onnx which use PEP 517 and cannot be installed directly" )

And when I extract the .onnx file of the clip text encoder, I have to use:

pytorch > 1.7.1
(clip/clip.py:23: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
/218019043/software/anaconda3/envs/dassl/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2378: UserWarning: Exporting aten::index operator of advanced indexing in opset 9 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results."))
===============================================================

When the .onnx file (gotten by pytorch > 1.7.1) is used in "python 2.7 && tensorflow 1.13 && onnx <1.7.0", an error will be "*** ValidationError: Your model ir_version is higher than the checker's."

**Comment by numb3r3** [comment]
Of course, the easiest solution is to upgrade your working environment. But I guess it is not donable for some special reasons. Is it possible to use docker container?

**Comment by numb3r3** [comment]
tbh, the jina will not support `python < 3.7`.  `python 2.7` supporting is not in our plan.

**Comment by username123062** [comment]
> tbh, the jina will not support `python < 3.7`. `python 2.7` supporting is not in our plan.

Thanks for your reply!
