### ISSUE TITLE
Rich traceback enabled by default

### ISSUE THREAD

**Issue by MrBeeMovie** [jina-ai/clip-as-service#724]
I am not sure if this is a jina issue or a clip-as-service issue but [traceback handling](https://rich.readthedocs.io/en/stable/traceback.html#traceback-handler) has been enabled by default as part of the rich library. If the user, me in this case, wants to disable traceback handling there is no way to do so. I think it would be better to allow the user to choose whether or not they want to install the handler. Thank you!

**Comment by hanxiao** [comment]
you can set environment variable `DA_NO_RICH_HANDLER` before the process starts to disable rich handler

**Comment by numb3r3** [comment]
Actually, the `DA_NO_RICH_HANDLER` is introduced in the dependency of package`docarray` and not documented yet. TBH, it is much trickier to involve this env variable  `DA_NO_RICH_HANDLER`.  Hope we will have an elegant way to control the traceback handling later. 

Anyway, thanks for your reporting, and hope this issue can help others who have the same concerns as you.
