### ISSUE TITLE
svg not correctly rendered in safari

### ISSUE THREAD

**Issue by ZiniuYu** [jina-ai/clip-as-service#732]
The svg in README is not correctly rendered in safari.

![image](https://user-images.githubusercontent.com/21340127/170406877-6bd9c62d-47c8-41a1-8516-914d5b389bec.png)

Chrome is fine.
![image](https://user-images.githubusercontent.com/21340127/170406978-8fde6707-4040-4b30-929d-dc62fbba505f.png)

**Comment by hanxiao** [comment]
looks like a simple problem but 10 days no action point, so close
