### ISSUE TITLE
Unable to run ONNX clip as service on GPU Machine 

### ISSUE THREAD

**Issue by Jitendradubey** [jina-ai/clip-as-service#733]
Hi All,

I am using clip as service on CUDA machine, with proper installation steps, follow the below steps:
Server with ONNX support
pip install "clip_server[onnx]"

Run ONNX Server
python -m clip_server onnx-flow.yml

Always running on CPU only, but i want to levearge GPU power and return the result as faster than CPU.
  
![ONN_Running_image](https://user-images.githubusercontent.com/7260090/170705930-ded3d4ca-b810-41da-9697-95d6c6d26e46.PNG)

NVIDIA and Versions
![nvidia-smi](https://user-images.githubusercontent.com/7260090/170706106-3a02af5e-3117-49c1-8206-bf94129945c0.PNG)

![nvcc-version](https://user-images.githubusercontent.com/7260090/170706137-717143e7-8d09-4773-ab07-d3a00628dbba.PNG)

Just want to know how to switch CPU to GPU using ONNX(Clip server) , to increase the CLIP inference result

Thanks In advance.

**Comment by numb3r3** [comment]
Based on the logging, I guess this is due to that the latest `onnxruntime-gpu` is not compatible with cuda 11.4.  Can you try to re-install `onnxruntime-gpu` with correct version by following https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by Jitendradubey** [comment]
@numb3r3 Thank you for quick response.

Now, I have changed the versioning of 'onnxruntime-gpu'  from 1.11 to 1.10,  but again not able to use GPU, check the below installed packages  
![again_error](https://user-images.githubusercontent.com/7260090/170822509-95f695a9-b9b8-47b0-bd56-16f41b595111.PNG)

And running again and again , still showing CPU utilizations, check the below image.
![Model resullt](https://user-images.githubusercontent.com/7260090/170822641-facda19f-9853-44d6-a80a-901ab5e63c37.PNG)

Please let me know if any other specific things were missing,

Thanks in Advance.

**Comment by numb3r3** [comment]
@Jitendradubey appreciate your time. From the logging, we can see that the installation of onnxruntie-gpu failed again. According to https://github.com/microsoft/onnxruntime/issues/7748#issuecomment-844358537, we can try the following steps: 
>  I uninstalled onnx as well this time and just installed onnxruntime-gpu from sctrach and that made it work,

**Comment by Jitendradubey** [comment]
Thnaks @numb3r3 !!

Able to run Onnxruntime-GPU.

reinstalled the onnx,onnxruntime, onnxruntime-gpu then reinstalled only onnxruntime-gpu
it is started working.

now, we can close this issue, thanks again!!

**Comment by shubhamgoel27** [comment]
Probably a bit late to this, but I've gotten success using the same process too.

**Comment by FrancescoSaverioZuppichini** [comment]
Same here, no success with the above strategy

**Comment by numb3r3** [comment]
@FrancescoSaverioZuppichini is there any error message we can review?

**Comment by numb3r3** [comment]
You rock!  I appreciate the effort. Maybe we need to put your tricks into our docs. That will help the community to fix the same issue quickly.
