### ISSUE TITLE
TensorRT is Running on GPU machine without any issue but still inference result of clip model is slower

### ISSUE THREAD

**Issue by Jitendradubey** [jina-ai/clip-as-service#734]
Hi,

Using the CUDA 11.4 and Other package also installed properly without any issue, and TensorRT is also running on my GPU CUDA machine, refering the below link for installation
https://clip-as-service.jina.ai/?utm_source=clip-as-service#

Installation packages:
![tensorrt_packages](https://user-images.githubusercontent.com/7260090/170707418-40ae8f4b-14ad-46f7-95cd-4c9482952366.PNG)

CUDA Version
![nvcc-version](https://user-images.githubusercontent.com/7260090/170707657-2d06f2a8-0efa-4a84-99fc-c07da623d4b9.PNG)
![nvidia-smi](https://user-images.githubusercontent.com/7260090/170707666-bf6e95fc-f31f-41c1-9a90-1609277c3851.PNG)

Code:

from clip_client import Client
from docarray import Document
import time
import glob
import os

c = Client(server='grpc://0.0.0.0:51000')
print(c)
t = time.time()
try:

    for row in range(1000):
        r = c.rank(
            [
                Document(
                   uri= 'https://raw.githubusercontent.com/jina-ai/clip-as-service/main/.github/README-img/rerank.png',
                    matches=[
                        Document(text=f'a photo of a {p}')
                        for p in (
                            'control room',
                            'lecture room',
                            'conference room',
                            'podium indoor',
                            'television studio',
                            
                        )
                    ],
                )
            ]
        )

        print(r['@m', ['text', 'scores__clip_score__value']])
except Exception as e:
    print("Error",e)
  
end = time.time() - t
print("ending time",end)

Using above code to get the inference result for 1000 iteration, around 222 second of time, which is very slow comparative normal CUDA inferences using CLIP model.

Please help me why i am not able to run faster while using the TensorRT of CLIP as service.

Thanks in advance.

**Comment by hanxiao** [comment]
your gpu screenshot shows is not utilizing GPU at all, @numb3r3 could you help on this one?

**Comment by numb3r3** [comment]
@Jitendradubey 
> Using above code to get the inference result for 1000 iteration, around 222 second of time, which is very slow comparative normal CUDA inferences using CLIP model.

Just want to clarify what's the *normal CUDA inference* in your test? using pytorch cuda inference via `python -m clip_server torch-flow.yml`? 

BTW, could you please provide the full logging?

**Comment by Jitendradubey** [comment]
@numb3r3 thanks!!
using pytorch cuda inference via `python -m clip_server torch-flow.yml?` 
Yes using the same, check the below image
![model1](https://user-images.githubusercontent.com/7260090/170823527-a7429b91-b996-48b7-92e7-b868c54b8ea2.PNG)

for this question - Just want to clarify what's the normal CUDA inference in your test? 
took 214 second of normal CUDA inference timings, check in below too
![model2](https://user-images.githubusercontent.com/7260090/170823552-f402cb00-4d23-4804-93d4-9d00f1553952.PNG)
# code which is i'm refering 
![code](https://user-images.githubusercontent.com/7260090/170823595-d9d21bff-a4bd-48e8-858a-12dc1823a3a4.PNG)

Hope this is useful.

Thanks

**Comment by Jitendradubey** [comment]
@numb3r3 thanks for prompt response.

definitely, will keep checking the progress on tensorRT.

Thanks!!
