### ISSUE TITLE
"ViT-L-14@336px" model name doesn't work with CLIPTorchEncoder.

### ISSUE THREAD

**Issue by delgermurun** [jina-ai/clip-as-service#799]
`ViT-L-14@336px` model name mentioned in the docs, but it doesn't work anymore.
```
    uses: jinahub+docker://CLIPTorchEncoder/latest-gpu
    uses_with:
      name: ViT-L-14@336px
```
----
But `ViT-L-14-336::openai` works.
```
    uses: jinahub+docker://CLIPTorchEncoder/latest-gpu
    uses_with:
      name: ViT-L-14-336::openai
```

**Comment by ZiniuYu** [comment]
Hi @delgermurun , it is a naming convention. We used to only support OpenAI models and they called it `ViT-L/14@336px` (left slash). After we switch to OpenCLIP models, we changed to `ViT-L-14-336::openai`. We kept the old names for backward compatibility. But I do think we need to clarify this or have higher fault tolerance on those names. Thanks for pointing this out!

**Comment by delgermurun** [comment]
below image is from https://hub.jina.ai/executor/gzpbl8jh

<img width="835" alt="Screenshot 2022-08-10 at 07 42 58" src="https://user-images.githubusercontent.com/492616/183824400-148b5d05-6a75-4d28-9d40-eeb33634f81a.png">

here even old name is wrong.
