### ISSUE TITLE
Specify Model to use

### ISSUE THREAD

**Issue by RaiAmanRai** [jina-ai/clip-as-service#802]
How can I specify what model to use. I have seen the documentation specifying which model is supported for pytorch, onnx and tensorrt, but there is no documentation for changing them.

@ZiniuYu  any help on this!

**Comment by ZiniuYu** [comment]
Hi @RaiAmanRai , you may take a look [here](https://clip-as-service.jina.ai/user-guides/server/#clip-model-config)
For example,
```{yaml}
jtype: Flow
version: '1'
with:
  port: 51000
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      metas:
        py_modules:
          - clip_server.executors.clip_torch
    uses_with:
      name: 'RN101::openai'
```

**Comment by RaiAmanRai** [comment]
Figured it out, thanks for the quick response @ZiniuYu
