### ISSUE TITLE
TensorRT for large models

### ISSUE THREAD

**Issue by RaiAmanRai** [jina-ai/clip-as-service#805]
Hi, are there any particular reasons why the TensorRT models for large architecture like ViT-L-14 and ViT-L-14@336@px are not supported?

I tried to convert onnx model for ViT-L-14@336px into trt myself, but could't due to an unsupported layer.

Any thoughts?

**Comment by ZiniuYu** [comment]
Hi @RaiAmanRai , thank you for asking! As you have mentioned, there are some unsupported operation issues and other things such as size limits, hardware compatibilities that need to be addressed before we can fully support those models. We are investigating those blockers and will support them in the future releases if possible. You are more than welcome to share any observations or solutions! Cheers 🍻

**Comment by RaiAmanRai** [comment]
Cheers and thanks for quick replies. Will surely share if I find anything unusual.
