### ISSUE TITLE
Finetuning for image-text ranking

### ISSUE THREAD

**Issue by RaiAmanRai** [jina-ai/clip-as-service#807]
Hi @ZiniuYu, I checked out the finetuner, amazing piece of work.

Is there any provision that i can finetune a clip model for image-text ranking task.

Can a finetuned model for text-to-iage task also work for image-text ranking task. Any ideas on this.

**Comment by ZiniuYu** [comment]
Hi @RaiAmanRai . In general, any image/text (any orders and combinations) encoding-related task can use the CLIP model and can be fine-tuned with a custom dataset. CLIP-as-service supports the use of custom pre-trained models in ONNX runtime. [See the instruction here.](https://clip-as-service.jina.ai/user-guides/finetuner/) You can also take a look at [the basic logic and introduction from OpenAI](https://openai.com/blog/clip/). 

Remember to join our community Slack channel to talk to our engineers and share thoughts with other people ✌️  
🔗 [slack.jina.ai](http://slack.jina.ai/)

**Comment by RaiAmanRai** [comment]
Thanks for the help @ZiniuYu, cheers
