### ISSUE TITLE
Onyx + TensorRT support for XLM-R Large Vit-B/16+?

### ISSUE THREAD

**Issue by NOT-HAL9000** [jina-ai/clip-as-service#822]
Just wondering if this is possible? Thanks!

**Comment by ZiniuYu** [comment]
Hi, thank you for asking! 

For ONNX it is possible, and it will be supported in future releases. Unfortunately, we have not yet planned to support TensorRT for M-CLIP models very soon. You may refer to https://github.com/ELS-RD/transformer-deploy and other online resources on converting PyTorch models to TensorRT.

**Comment by NOT-HAL9000** [comment]
> For ONNX it is possible, and it will be supported in future releases

Thanks! Is there a roadmap with a rough ETA for the ONYX runtime for M-CLIP models?

**Comment by numb3r3** [comment]
It's hard to offer the exact timeline for supporting ONNX M-CLIP models. However, It's hopefully we can release it by end of this month.

**Comment by numb3r3** [comment]
@NOT-HAL9000 I'm glad to say now, ONNX M-CLIP models have been enabled in the latest version. Please play it around, and leave your comments.

**Comment by NOT-HAL9000** [comment]
@numb3r3 Thank you!
