### ISSUE TITLE
using finetuned model

### ISSUE THREAD

**Issue by RaiAmanRai** [jina-ai/clip-as-service#826]
Hi @ZiniuYu , if I use Jina-Finetuner to finetune a L-14 model on a custom dataset, does it returns me an onnx model and if I use some other platform, say colab to finetune a model how can I export it to onnx and use it with clip-as-service ?

**Comment by ZiniuYu** [comment]
Yes, Finetuner returns ONNX models but with richer information needed by CLIP-as-service. Refer [here](https://clip-as-service.jina.ai/user-guides/finetuner/#finetuner) for instructions on using finetuned ONNX models in CLIP-as-service.

**Comment by RaiAmanRai** [comment]
@ZiniuYu 
thanks for quick reply. I also wanted to know if say i have a finetuned model but its not in onnx. Can I convert it to onnx using this, given clip-as-service has a support for that architecture in onnx
