### ISSUE TITLE
dimension

### ISSUE THREAD

**Issue by 161424** [jina-ai/clip-as-service#827]
I want to get word embedding, but 512 dimensions are too big for me. Can I output smaller dimensions, similar to 128 dimensions

**Comment by numb3r3** [comment]
In general, you can simply use an unsupervised method, PCA to reduce the dimension. But PCA would degrade the accuracy a bit. BTW, what's your use case to have lower-dimension embeddings?

**Comment by 161424** [comment]
I just want to get word vectors now, but it may be that I have selected too many features, which leads to the saved file being a little large. Let me try to reduce it from other aspects first, and then try to modify the dimension
