### ISSUE TITLE
Retrieve authentication token in client side using hubble.get_token

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/clip-as-service#837]
Currently, users who want to authenticate to clip-as-service, need to perform 2 steps:
1. login using CLI or jina hub website
2. retrieve and explicitly set the auth token either in environment variable or in the clip-client API.

It would be great if login using CLI were enough (`jina auth login`). This implies that we retrieve the auth token using hubble.get_token (in addition to the existing methods).

**Comment by numb3r3** [comment]
@alaeddine-13 The granted user is not necessary a jina registered user. For example, I created a jina account and create a TOKEN. Then I can share this TOKEN with anybody (e.g., my teammate). Generall, IMO, the authentication token works for the consumer. `jina auth login` works for the producer. So, at this moment, I would not merge them to make the logic confusing.

**Comment by ZiniuYu** [comment]
Stay tuned for the inference_client :)
