### ISSUE TITLE
Why are you fast？

### ISSUE THREAD

**Issue by wqh17101** [jina-ai/clip-as-service#855]
What is the difference between you and the common grpc service with multiprocessing of preprocessing and inference?

**Comment by ZiniuYu** [comment]
Hi @wqh17101 , 

CLIP-as-service is a modern, easy-to-use, fast, and elastic inference service for CLIP models. 

It has a minimalist design on both the client and server sides, and provides an intuitive and consistent API for image and sentence embedding. It also supports async clients and can easily switch between gRPC, HTTP, and WebSocket protocols with TLS and compression. The APIs are carefully designed to handle large inputs into smaller batches with lower memory footprint. You can scale the service easily by setting replicas and sharding in one line. 

It also integrates smoothly with the [Jina](https://jina.ai) ecosystem, allowing you to build cross-modal and multi-modal solutions quickly and easily. Jina handles the infrastructure complexity, making advanced solution engineering and cloud-native technologies accessible to every developer. You can also access free CPU/GPU hosting via [Jina Cloud](https://cloud.jina.ai).

You can easily build many interesting applications based on CLIP-as-service's 4 main functionalities: encoding, ranking, indexing and searching. You can take a look at some examples provided by us: [Text & Image Embedding](https://clip-as-service.jina.ai/playground/embedding/), [Visual Reasoning](https://clip-as-service.jina.ai/playground/reasoning/) and [Text & Image Searching](https://clip-as-service.jina.ai/playground/searching/). Learn more about CLIP-as-service from our [docs](https://clip-as-service.jina.ai/).

We also have an always online clip service for you to encode and rank contents. You can focus on your core logic and leave the infrastructure to us. Try it out [here](https://console.clip.jina.ai/get_started) 🚀

**Comment by wqh17101** [comment]
Yeah，i want to learn the key reason of how to be so fast.
Is the map_batch make you fast?
https://github.com/jina-ai/clip-as-service/blob/710862279bdef342983bd7944f413d8ee54f9603/server/clip_server/executors/clip_torch.py#L147-L163
![image](https://user-images.githubusercontent.com/26429138/201251095-6af55e61-c16a-45db-a21b-4801eb4bed5c.png)

**Comment by numb3r3** [comment]
good catch, this is one tech trick we use to utilize multi-threads for data preprocessing. But I don't think this `map_batch` is the key reason. Most of the performance would come from the advances of `Jina` and `docarray`. Especially, `docarray` is a data structure with good performance in transit.
