### ISSUE TITLE
how to transform CLIP to TensorRT, ONNX, TorchScript?

### ISSUE THREAD

**Issue by FD-Liekkas** [jina-ai/clip-as-service#878]
Could you please share the processing code of converting the original CLIP to TensorRT, ONNX, TorchScript model?

**Comment by ZiniuYu** [comment]
Hi, there are many tutorials online. For example

Pytorch->ONNX https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html
PyTorch->TorchScript https://pytorch.org/tutorials/recipes/torchscript_inference.html
ONNX->TensorRT https://docs.nvidia.com/deeplearning/tensorrt/quick-start-guide/index.html
