### ISSUE TITLE
Does it support multiple gpu's running simultaneously on one machine? Maximize inference speed

### ISSUE THREAD

**Issue by ScottishFold007** [jina-ai/clip-as-service#886]
Does it support multiple gpu's running simultaneously on one machine? Maximize inference speed

**Comment by ZiniuYu** [comment]
Hi, please refer [here](https://clip-as-service.jina.ai/user-guides/server/#serve-on-multiple-gpus) for multiple GPU serving 🍻

**Comment by jemmyshin** [comment]
Please use replicate executor and replicate GPUs, following this: https://docs.jina.ai/concepts/flow/scale-out/
