### ISSUE TITLE
Is there a plan to support the latest pretrained ViT CLIP model (ViT-G/14 on LAION-2B) ?

### ISSUE THREAD

**Issue by joyjayng** [jina-ai/clip-as-service#912]
[ViT-G/14 on LAION-2B with an accuracy of 80.1.](https://github.com/mlfoundations/open_clip/blob/main/README.md) The best in1k zero-shot for released, open-source weights thus far.

**Comment by ZiniuYu** [comment]
Hi @joyjayng ,

Thank you for your interest in clip-as-service and for reaching out to us with your question. We appreciate your feedback and are glad to know that you are interested in using the latest ViT CLIP model (ViT-G/14 on LAION-2B) with our project.

Unfortunately, we currently may not have the capacity to prioritize support for this specific model. However, we encourage you to contribute to our project by submitting a pull request with the necessary changes to add support for this model. We welcome contributions from the community, and we will be happy to review and merge your changes if they meet our standards and requirements.

In case you need guidance on how to add support for new models or any other aspect of our project, please feel free to reach out to us, and we'll do our best to help you.

We look forward to your contribution.
