### ISSUE TITLE
cn_clip miss & unexpected keyword argument 'global_average_pool'

### ISSUE THREAD

**Issue by SecretSun** [jina-ai/clip-as-service#939]
Dear official colleagues,

branches: main，0.8.2？

I am writing to request assistance with the following problems I am having with the clip-as-service project:

1. The base image is missing cn_clip.
2. After packaging and running the main code directly using server.Dockerfile, an unexpected keyword argument "global_average_pool" is displayed.

I have attached the relevant error messages.

I would be grateful if you could provide any assistance you can.

Thank you for your time and consideration.

**Comment by zhaijunxiao** [comment]
hi, You can refer to this link. it works for me。

https://github.com/jina-ai/clip-as-service/issues/937#issuecomment-1791025746
